Repository PEC-CSS/slowmokit, pull requests merged in 2023-02, with the labels that each got.

#46 Written matrix interface and implemented basic functions
  CMakeLists.txt
  examples/cluster/kMeans.cpp
  examples/linear_model/linear_regression.cpp
  examples/matrix.cpp
  src/slowmokit/ducks/ducks.hpp
  src/slowmokit/ducks/matrix/matrix.cpp
  src/slowmokit/ducks/matrix/matrix.hpp
  src/slowmokit/methods/cluster/kMeans/kMeans.hpp
  src/slowmokit/models/model.hpp
Labels: pwoc, hard

#51 Implemented accuracy
  CMakeLists.txt
  examples/accuracy_eg.cpp
  src/slowmokit/methods/metrics/accuracy
  src/slowmokit/methods/metrics/accuracy.cpp
  src/slowmokit/methods/metrics/accuracy.hpp
Labels: pwoc, easy

#71 one hot encoder commited
  CMakeLists.txt
  examples/preprocessing/one_hot_encoder_eg.cpp
  src/slowmokit/methods/preprocessing/one_hot_encoder.cpp
  src/slowmokit/methods/preprocessing/one_hot_encoder.hpp
Labels: pwoc, easy

#84 Implementation of accuracy and precision #38
  CMakeLists.txt
  examples/metrics/precision_eg.cpp
  examples/metrics/recall_eg.cpp
  src/slowmokit/methods/metrics/precision.cpp
  src/slowmokit/methods/metrics/precision.hpp
  src/slowmokit/methods/metrics/recall.cpp
  src/slowmokit/methods/metrics/recall.hpp
Labels: pwoc, medium

#80 Multiclass Logistic Regression Model
  CMakeLists.txt
  docs/methods/linear_model/logistic_regression.md
  docs/methods/neighbors/bernoulli_nb/bernoulli_nb.md
  docs/methods/neighbors/gaussian_nb/gaussian_nb.md
  examples/linear_model/logistic_regression.cpp
  src/slowmokit.hpp
  src/slowmokit/methods/linear_model/logistic_regression.hpp
  src/slowmokit/methods/linear_model/logistic_regression/logistic_regression.cpp
  src/slowmokit/methods/linear_model/logistic_regression/logistic_regression.hpp
Labels: pwoc, hard

#93 Implemented MSE
  CMakeLists.txt
  docs/methods/metrics/accuracy.md
  docs/methods/metrics/mean_squared_error.md
  docs/methods/metrics/precision.md
  docs/methods/metrics/recall.md
  docs/methods/preprocessing/normalization.md
  docs/methods/preprocessing/standardization.md
  examples/metrics/mean_squared_error_eg.cpp
  src/slowmokit/methods/metrics/mean_squared_error.cpp
  src/slowmokit/methods/metrics/mean_squared_error.hpp
Labels: pwoc, medium

#94 Docs-added
  docs/methods/neighbors/knn/knn.md
Labels: pwoc, easy

#96 Classification_report.md Added
  docs/methods/metrics/classification_report.md
Labels: pwoc, easy

#97 added label_encoder.md
  docs/methods/preprocessing/label_encoder.md
Labels: pwoc, easy

#98 Silhouette Score added.
  CMakeLists.txt
  docs/methods/metrics/silhouette_score.md
  examples/metrics/silhouette_score.cpp
  src/slowmokit/methods/metrics/silhouette_score.cpp
  src/slowmokit/methods/metrics/silhouette_score.hpp
Labels: pwoc, medium
